sudo: false
os:
    - osx
    - linux
language:
    - c
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - libsamplerate-dev
            - libsndfile-dev
            - libasound2-dev
            - libdb-dev
            - doxygen

before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated pkg-config || brew upgrade pkg-config; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libsamplerate; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libsndfile; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install readline; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install berkeley-db; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install doxygen; fi

script:
    - ./autogen.sh
    - ./configure
    - make
